version: '3.8'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    tty: true
